"""Core domain models used throughout the cTrade application.

These are pure data models (not ORM models) used for passing data between components.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any
from uuid import UUID, uuid4


def _utc_now() -> datetime:
    """Timezone-aware UTC now (avoids deprecated datetime.utcnow)."""
    return datetime.now(timezone.utc)

from ctrade.core.enums import (
    AlertSeverity,
    OrderSide,
    OrderStatus,
    OrderType,
    PositionSide,
    PositionStatus,
    SentimentLabel,
    SignalAction,
    Timeframe,
    TradingMode,
)


@dataclass(frozen=True)
class Candle:
    """OHLCV candlestick data point."""

    time: datetime
    pair_symbol: str
    timeframe: Timeframe
    open: Decimal
    high: Decimal
    low: Decimal
    close: Decimal
    volume: Decimal


@dataclass(frozen=True)
class Signal:
    """Trading signal generated by the analysis layer."""

    id: UUID = field(default_factory=uuid4)
    pair_symbol: str = ""
    action: SignalAction = SignalAction.HOLD
    confidence: float = 0.0
    technical_score: float | None = None
    sentiment_score: float | None = None
    onchain_score: float | None = None
    contributing_factors: dict[str, Any] = field(default_factory=dict)
    strategy_name: str = ""
    created_at: datetime = field(default_factory=_utc_now)


@dataclass
class Order:
    """Order to be placed or already placed on an exchange."""

    id: UUID = field(default_factory=uuid4)
    signal_id: UUID | None = None
    pair_symbol: str = ""
    exchange_name: str = ""
    trading_mode: TradingMode = TradingMode.PAPER
    order_type: OrderType = OrderType.MARKET
    side: OrderSide = OrderSide.BUY
    quantity: Decimal = Decimal("0")
    price: Decimal | None = None
    stop_price: Decimal | None = None
    status: OrderStatus = OrderStatus.PENDING
    filled_quantity: Decimal = Decimal("0")
    avg_fill_price: Decimal | None = None
    fee: Decimal = Decimal("0")
    fee_currency: str = ""
    exchange_order_id: str | None = None
    error_message: str | None = None
    created_at: datetime = field(default_factory=_utc_now)
    updated_at: datetime = field(default_factory=_utc_now)
    filled_at: datetime | None = None


@dataclass
class Position:
    """An open or closed trading position."""

    id: UUID = field(default_factory=uuid4)
    pair_symbol: str = ""
    exchange_name: str = ""
    trading_mode: TradingMode = TradingMode.PAPER
    side: PositionSide = PositionSide.LONG
    status: PositionStatus = PositionStatus.OPEN
    entry_price: Decimal = Decimal("0")
    exit_price: Decimal | None = None
    quantity: Decimal = Decimal("0")
    stop_loss: Decimal | None = None
    take_profit: Decimal | None = None
    realized_pnl: Decimal | None = None
    realized_pnl_pct: Decimal | None = None
    fees_total: Decimal = Decimal("0")
    strategy_name: str = ""
    entry_signal_id: UUID | None = None
    exit_signal_id: UUID | None = None
    opened_at: datetime = field(default_factory=_utc_now)
    closed_at: datetime | None = None


@dataclass(frozen=True)
class Ticker:
    """Current price ticker for a trading pair."""

    pair_symbol: str
    last_price: Decimal
    bid: Decimal
    ask: Decimal
    high_24h: Decimal
    low_24h: Decimal
    volume_24h: Decimal
    change_pct_24h: float
    timestamp: datetime


@dataclass(frozen=True)
class SentimentDataPoint:
    """A single sentiment measurement from a feed source."""

    asset: str
    source: str
    source_id: str | None = None
    raw_text: str = ""
    label: SentimentLabel = SentimentLabel.NEUTRAL
    score: float = 0.0
    model_used: str = ""
    timestamp: datetime = field(default_factory=_utc_now)


@dataclass(frozen=True)
class OnChainMetric:
    """A single on-chain metric data point."""

    asset: str
    metric_name: str
    metric_value: Decimal
    source: str = ""
    timestamp: datetime = field(default_factory=_utc_now)


@dataclass(frozen=True)
class MarketState:
    """Snapshot of all market data for a trading pair, used by strategies."""

    pair_symbol: str
    current_price: Decimal
    candles: list[Candle] = field(default_factory=list)
    technical_score: float | None = None
    sentiment_score: float | None = None
    onchain_score: float | None = None
    timestamp: datetime = field(default_factory=_utc_now)


@dataclass(frozen=True)
class PortfolioSnapshot:
    """Point-in-time snapshot of portfolio state."""

    exchange_name: str
    trading_mode: TradingMode
    total_value_usd: Decimal
    cash_balance: dict[str, Decimal] = field(default_factory=dict)
    open_positions: int = 0
    unrealized_pnl: Decimal = Decimal("0")
    timestamp: datetime = field(default_factory=_utc_now)


@dataclass(frozen=True)
class Alert:
    """An alert notification to be dispatched."""

    message: str
    severity: AlertSeverity = AlertSeverity.INFO
    alert_type: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=_utc_now)
