"""SQLAlchemy ORM models for all database tables."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    LargeBinary,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _new_uuid() -> uuid.UUID:
    return uuid.uuid4()


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    pass


class ExchangeModel(Base):
    """Configured exchange references."""

    __tablename__ = "exchanges"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=_new_uuid)
    name: Mapped[str] = mapped_column(String(50), unique=True, nullable=False)
    exchange_type: Mapped[str] = mapped_column(String(20), nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    config_json: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utc_now)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utc_now, onupdate=_utc_now
    )

    # Relationships
    trading_pairs: Mapped[list[TradingPairModel]] = relationship(back_populates="exchange")
    credentials: Mapped[list[ApiCredentialModel]] = relationship(back_populates="exchange")


class TradingPairModel(Base):
    """Trading pairs being monitored."""

    __tablename__ = "trading_pairs"
    __table_args__ = (UniqueConstraint("exchange_id", "symbol", name="uq_exchange_symbol"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=_new_uuid)
    exchange_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("exchanges.id"), nullable=False
    )
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    base_currency: Mapped[str] = mapped_column(String(10), nullable=False)
    quote_currency: Mapped[str] = mapped_column(String(10), nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    min_order_size: Mapped[float | None] = mapped_column(Numeric(20, 8), nullable=True)
    price_precision: Mapped[int | None] = mapped_column(Integer, nullable=True)
    qty_precision: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utc_now)

    # Relationships
    exchange: Mapped[ExchangeModel] = relationship(back_populates="trading_pairs")


class CandleModel(Base):
    """OHLCV candle data (designed for TimescaleDB hypertable)."""

    __tablename__ = "candles"
    __table_args__ = (
        Index("ix_candles_pair_time", "pair_id", "time"),
    )

    time: Mapped[datetime] = mapped_column(DateTime(timezone=True), primary_key=True)
    pair_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    timeframe: Mapped[str] = mapped_column(String(5), primary_key=True)
    open: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    high: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    low: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    close: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    volume: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)


class SignalModel(Base):
    """Signals generated by the analysis layer."""

    __tablename__ = "signals"
    __table_args__ = (
        Index("ix_signals_pair_created", "pair_id", "created_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=_new_uuid)
    pair_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    strategy_name: Mapped[str] = mapped_column(String(100), nullable=False)
    action: Mapped[str] = mapped_column(String(10), nullable=False)
    confidence: Mapped[float] = mapped_column(Numeric(5, 4), nullable=False)
    technical_score: Mapped[float | None] = mapped_column(Numeric(5, 4), nullable=True)
    sentiment_score: Mapped[float | None] = mapped_column(Numeric(5, 4), nullable=True)
    onchain_score: Mapped[float | None] = mapped_column(Numeric(5, 4), nullable=True)
    derivatives_score: Mapped[float | None] = mapped_column(Numeric(5, 4), nullable=True)
    market_sentiment_score: Mapped[float | None] = mapped_column(Numeric(5, 4), nullable=True)
    cvd_score: Mapped[float | None] = mapped_column(Numeric(5, 4), nullable=True)
    social_velocity_score: Mapped[float | None] = mapped_column(Numeric(5, 4), nullable=True)
    contributing_factors: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utc_now)


class OrderModel(Base):
    """Orders placed (both paper and live)."""

    __tablename__ = "orders"
    __table_args__ = (
        Index("ix_orders_pair_created", "pair_id", "created_at"),
        Index("ix_orders_status", "status"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=_new_uuid)
    signal_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    pair_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    exchange_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    trading_mode: Mapped[str] = mapped_column(String(10), nullable=False)
    order_type: Mapped[str] = mapped_column(String(20), nullable=False)
    side: Mapped[str] = mapped_column(String(4), nullable=False)
    quantity: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    price: Mapped[float | None] = mapped_column(Numeric(20, 8), nullable=True)
    stop_price: Mapped[float | None] = mapped_column(Numeric(20, 8), nullable=True)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="pending")
    filled_quantity: Mapped[float] = mapped_column(Numeric(20, 8), default=0)
    avg_fill_price: Mapped[float | None] = mapped_column(Numeric(20, 8), nullable=True)
    fee: Mapped[float] = mapped_column(Numeric(20, 8), default=0)
    fee_currency: Mapped[str | None] = mapped_column(String(10), nullable=True)
    exchange_order_id: Mapped[str | None] = mapped_column(String(100), nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utc_now)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utc_now, onupdate=_utc_now
    )
    filled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class PositionModel(Base):
    """Positions (aggregated view of related orders)."""

    __tablename__ = "positions"
    __table_args__ = (
        Index("ix_positions_status", "status"),
        Index("ix_positions_pair_status", "pair_id", "status"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=_new_uuid)
    pair_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    exchange_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    trading_mode: Mapped[str] = mapped_column(String(10), nullable=False)
    side: Mapped[str] = mapped_column(String(5), nullable=False)
    status: Mapped[str] = mapped_column(String(10), nullable=False, default="open")
    entry_price: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    exit_price: Mapped[float | None] = mapped_column(Numeric(20, 8), nullable=True)
    quantity: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    stop_loss: Mapped[float | None] = mapped_column(Numeric(20, 8), nullable=True)
    take_profit: Mapped[float | None] = mapped_column(Numeric(20, 8), nullable=True)
    realized_pnl: Mapped[float | None] = mapped_column(Numeric(20, 8), nullable=True)
    realized_pnl_pct: Mapped[float | None] = mapped_column(Numeric(10, 4), nullable=True)
    fees_total: Mapped[float] = mapped_column(Numeric(20, 8), default=0)
    strategy_name: Mapped[str | None] = mapped_column(String(100), nullable=True)
    entry_signal_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    exit_signal_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    opened_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utc_now)
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    metadata_json: Mapped[dict | None] = mapped_column(JSONB, nullable=True)


class PortfolioSnapshotModel(Base):
    """Portfolio snapshots (periodic balance tracking)."""

    __tablename__ = "portfolio_snapshots"
    __table_args__ = (
        Index("ix_snapshots_exchange_mode_time", "exchange_id", "trading_mode", "time"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    time: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utc_now, index=True)
    exchange_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    trading_mode: Mapped[str] = mapped_column(String(10), nullable=False)
    total_value_usd: Mapped[float] = mapped_column(Numeric(20, 2), nullable=False)
    cash_balance: Mapped[dict] = mapped_column(JSONB, nullable=False)
    open_positions: Mapped[int] = mapped_column(Integer, default=0)
    unrealized_pnl: Mapped[float | None] = mapped_column(Numeric(20, 2), nullable=True)


class SentimentDataModel(Base):
    """Sentiment data points from feeds."""

    __tablename__ = "sentiment_data"
    __table_args__ = (
        Index("ix_sentiment_asset_time", "asset", "time"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    time: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utc_now)
    asset: Mapped[str] = mapped_column(String(10), nullable=False)
    source: Mapped[str] = mapped_column(String(20), nullable=False)
    source_id: Mapped[str | None] = mapped_column(String(200), nullable=True)
    raw_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    sentiment_label: Mapped[str | None] = mapped_column(String(10), nullable=True)
    sentiment_score: Mapped[float | None] = mapped_column(Numeric(5, 4), nullable=True)
    model_used: Mapped[str | None] = mapped_column(String(50), nullable=True)
    metadata_json: Mapped[dict | None] = mapped_column(JSONB, nullable=True)


class OnChainMetricModel(Base):
    """On-chain metrics data points."""

    __tablename__ = "onchain_metrics"
    __table_args__ = (
        Index("ix_onchain_asset_time", "asset", "time"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    time: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utc_now)
    asset: Mapped[str] = mapped_column(String(10), nullable=False)
    metric_name: Mapped[str] = mapped_column(String(100), nullable=False)
    metric_value: Mapped[float] = mapped_column(Numeric(30, 8), nullable=False)
    source: Mapped[str | None] = mapped_column(String(50), nullable=True)


class AlertConfigModel(Base):
    """Alert configurations."""

    __tablename__ = "alert_configs"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=_new_uuid)
    alert_type: Mapped[str] = mapped_column(String(50), nullable=False)
    conditions: Mapped[dict] = mapped_column(JSONB, nullable=False)
    channels: Mapped[dict] = mapped_column(JSONB, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utc_now)


class AlertHistoryModel(Base):
    """Alert delivery history."""

    __tablename__ = "alert_history"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    alert_config_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    severity: Mapped[str] = mapped_column(String(10), nullable=False)
    delivered_to: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utc_now)


class AuditLogModel(Base):
    """Audit log for all trade-related actions."""

    __tablename__ = "audit_log"
    __table_args__ = (
        Index("ix_audit_log_event_type", "event_type"),
        Index("ix_audit_log_created_at", "created_at"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    event_type: Mapped[str] = mapped_column(String(50), nullable=False)
    entity_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    entity_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    details: Mapped[dict] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utc_now)


class LogEntryModel(Base):
    """Persisted application log entries."""

    __tablename__ = "log_entries"
    __table_args__ = (
        Index("ix_log_entries_timestamp", "timestamp"),
        Index("ix_log_entries_level_ts", "level", "timestamp"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    level: Mapped[str] = mapped_column(String(10), nullable=False)
    logger: Mapped[str] = mapped_column(String(255), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    module: Mapped[str] = mapped_column(String(100), nullable=False, default="")
    func: Mapped[str] = mapped_column(String(100), nullable=False, default="")
    lineno: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utc_now)


class ApiCredentialModel(Base):
    """Encrypted exchange API credentials."""

    __tablename__ = "api_credentials"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=_new_uuid)
    exchange_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("exchanges.id"), nullable=False
    )
    label: Mapped[str | None] = mapped_column(String(100), nullable=True)
    api_key_enc: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    api_secret_enc: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    passphrase_enc: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)
    permissions: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utc_now)

    # Relationships
    exchange: Mapped[ExchangeModel] = relationship(back_populates="credentials")


class RuntimeConfigModel(Base):
    """Runtime-modifiable configuration stored in database."""

    __tablename__ = "runtime_config"

    key: Mapped[str] = mapped_column(String(100), primary_key=True)
    value: Mapped[dict] = mapped_column(JSONB, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utc_now, onupdate=_utc_now
    )
    updated_by: Mapped[str] = mapped_column(String(50), default="system")
